[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc = "0.8.18"
test = "test"
script = "script"
broadcast = "broadcast"
optimizer = true
optimizer_runs = 200
ffi = true

# [rpc_endpoints]
# mumbai = "${MUMBAI_RPC_URL}"



# See more config options https://github.com/foundry-rs/foundry/tree/master/config
